### ISSUE TITLE
Exo player needs default audio language setting 

### ISSUE THREAD

**Issue by Zizou3000** [synclerd/syncler#103]
Please add an option to select default audio language in exo player

**Comment by synclerd** [comment]
Settings > App Management > Preferred language.

**Comment by Zizou3000** [comment]
Thanks for checking it, but that's for subtitles, right? One will often
prefer English language as default for AUDIO and other for subtitles, is that
possible?

Or did you change something?

If you select English as language for audio, you'll also get subtitles for
it, which is undesirable because there will be too many subtitles with
other language(s) you selected.

Typical scenario user wants is English for AUDIO and it's own language for SUBTITLES. 

I think separate setting for preferred audio language  would be better.

Thank you

**Comment by Zizou3000** [comment]
If you select English as language for audio, you'll also get subtitles for
it, which is undesirable because there will be too many subtitles with
other language(s) you selected.

I think separate setting for preferred audio language only would be better.
