### ISSUE TITLE
[Feature] "Similar" on details pages posters

### ISSUE THREAD

**Issue by oathzed** [synclerd/syncler#11]
Please give us an option to change these back to posters instead of just backdrops

Also underneath them put year first then star rating.
(Do this for "search" items aswell)

**Comment by brugsbells** [comment]
This would be great. I would also like the ability to increase the size of similar items. They are way too small in tv layout.

On a related note, all the star ratings in similar and search are showing as 5 stars for some reason.

**Comment by ghost** [comment]
Yes, please. Posters or landscapes would be great.
