### ISSUE TITLE
Spurious results from beta

### ISSUE THREAD

**Issue by h53h54h55** [synclerd/syncler#125]
I am a vendor provider and have been checking our json files against v1 and beta. Beta seems not to be as efficient at searching as v1. I.e 911, Tracker, Equalizer, Spinning Out to name but a few return hundreds of links to other programmes. I.e 911 on some sources is 9.1.1 or 9-1-1 so it's hit and miss if the title search will find it but then the season and episode codes are being used so it pulls every program with a season 7 episode 5 for example. I also found results where it had matched to the hash key (as it had 911 in it somewhere). As developers we need a clearer understanding of what parameters and operands we can include in the json files - in v1 it seems {title} {year} means title AND year but in beta it's being used as title OR year ( if that makes sense). This is becoming a contentious issue on the forums. Thanks.

**Comment by synclerd** [comment]
Yes this is a beta issue. It is due to filtering logic in the app, not the provider. 
This will be fixed in the future updates of the beta. Provider devs won't need to do anything to fix this.

For all available variables you should see [this](https://github.com/synclerd/package-starter#available-variables)

Using {title} {year} should send a search request to the respective site with the keyword in that format. i.e `A MOVIE NAME 2000`.

I agree better documentation will help everyone. Let me know if you need further clarification.

**Comment by h53h54h55** [comment]
Thank you. Appreciate the response. I will do what I can on forums to stop other logging the same issue in the future. If there is a more efficient way to communicate please do let me know. I seem to be the only one updating scrapers at the moment and my provider url is the only one containing multiple packages - which itself is throwing up a few testing issues potentially for you. Thanks again

**Comment by synclerd** [comment]
No worries. Good luck with your development. If it's a bug or documentation issue, feel free to reach out here. Failing that, reddit PM is also an option.

**Comment by h53h54h55** [comment]
Thanks - I do have another question (let me know if you want me to assign this to an issue rather than addressing it in a thread)…

My file has several package options for users.  The manifest file carries a version number (numeric) and the individual package files also have their own version number (numeric).  These version numbers don’t seem to do anything?  No matter what I set my versioning to in my files to keep track of my changes - it remains at V1 on the app.  I also noted that auto updating (or even manually updating) will fail - I’m assuming maybe because I’m incrementing the version numbers incorrectly?  My assumption is the version number in the manifest file doesn’t change unless there is a structure change to the package list and the version number in the packages changes as they are updated (which for me is quite a lot a the moment as I sanitize the URLs).

So - what triggers syncler to perform any update (does it just blindly update or does it look to see if the version number has changed somewhere and then perform an update)?  Why doesn’t the version number show (I’ve now taken to writing the version number in the filename so I know what version users are having issue with).  Is there an documentation covering this / requirements you have that we need to fulfill in order for things to update without erroring?

Cheers
