### ISSUE TITLE
[Feature] Android TV Home star ratings

### ISSUE THREAD

**Issue by ssenior45** [synclerd/syncler#14]
On the Android TV Home screen everything seems to be rated 5 stars for me which doesn't match up when I launch Syncler and see the IMDB, RT etc ratings.

Example:

![IMG_0205](https://user-images.githubusercontent.com/6702942/122962679-8e7f1d00-d37d-11eb-9549-5005efe8a90b.jpg)

So "The Birthday Cake" seems awesome with 5 stars but when we click into it...

![IMG_0206](https://user-images.githubusercontent.com/6702942/122962800-ace51880-d37d-11eb-9be3-d630851e774b.jpg)

It actually looks pretty bad.

I'm not sure what source you currently use for the TV/Movie ratings on the home screen.

Would it be possible for this to be a choice for the user in Syncler options? i.e. which ratings source would you like to show on the Android TV Home screen. E.g. If I had selected RT as my source (18/100) in the above e.g. then on the home screen this would be 1 star and not 5 star.

I'm not sure if this is possible but what would be even better in my opinion is to replace the stars on the home screen with a source logo and a percentage like Google do on their TV e.g.

![IMG_0207](https://user-images.githubusercontent.com/6702942/122962894-bec6bb80-d37d-11eb-93a6-341144daac26.png)

See the way they use the RT logo then a percentage.

Maybe you could actually pass all of the available ratings through if there is enough room to display them.

**Comment by brugsbells** [comment]
This also occurs in the "Similar" section and when searching. Everything is showing 5 stars.

**Comment by ssenior45** [comment]
I tested this on the 1.3 beta and the issue still remains despite the changelog stating it has been fixed.

**Comment by ssenior45** [comment]
This is now fixed in the 1.3.0.1 release.
