### ISSUE TITLE
Regex in "json_format"

### ISSUE THREAD

**Issue by brentonv** [synclerd/syncler#145]
Does regex in "json_format" work?

```
        "json_format": {
            "title": "title",
            "peers": "peers",
            "seeds": "seeds",
            "size": "size",
            "hash": "hash.split('|')[1]"
        }
```

I can't get a result using this basic split

**Comment by synclerd** [comment]
Please see https://github.com/synclerd/package-starter#provider1

**Comment by brentonv** [comment]
There also seems to be a problem with sub results so I expect this is related to issues that were addressed in beta:

> - Fix: express provider does not handle json_format.sub_results correctly
> - Fix: express provider does not handle movie year when json_format is used
> - Fix: express provider does not catch http errors

**Comment by synclerd** [comment]
This is not supported. It should be `"hash": "hash". Otherwise you'll have to use kosmos provider unfortunately.

**Comment by synclerd** [comment]
> There also seems to be a problem with sub results so I expect this is related to issues that were addressed in beta:
> 
> > * Fix: express provider does not handle json_format.sub_results correctly
> > * Fix: express provider does not handle movie year when json_format is used
> > * Fix: express provider does not catch http errors

Please provide sample test case. Do not post infringing material please.

**Comment by brentonv** [comment]
No regex explains why it's not working and there's no need for examples if you suggest "hash": "hash.sub" will work. I think I was using a combination of both
