### ISSUE TITLE
Add TorBox as Debrid

### ISSUE THREAD

**Issue by Wamy-Dev** [synclerd/syncler#148]
TorBox is a newer debrid, but is cheaper, has more features, and doesn't have any IP streaming restrictions, among other things. I own TorBox and would love to also use Syncler (as would many of my users) with TorBox. I can provide Pro accounts for development. We have a fully-fledged API available at https://api-docs.torbox.app.

**Comment by brentonv** [comment]
Would be helpful right now

**Comment by rikin93** [comment]
Please implement this, real debrid is effectively useless now. We need newer non france based debrid service.

See article https://torrentfreak.com/real-debrid-implements-extreme-anti-piracy-filters-to-appease-film-companies-241122/

**Comment by LORDNORM** [comment]
Yes please bring it on

**Comment by arodriguezgb** [comment]
+1 would really like to see support for torbox

**Comment by Despaireon** [comment]
We would be most greatful for your cooperation😌

**Comment by Santaklawz** [comment]
Please add this and easynews if possible

**Comment by Uzzbro1211** [comment]
This is going to be super important in the coming days. Please add.

**Comment by joefast77** [comment]
waiting patiently dev 🙏🙏

**Comment by hackadelic** [comment]
+1 for sure definitely needed!

**Comment by ItsMikesch** [comment]
+1 Looks like now is the best time to have this added to Syncler v1 and v2!

**Comment by rphv4eva** [comment]
Alternatives are always welcome!

**Comment by drewb0y** [comment]
Please add torbox! It'll make an awesome app even awesomer (sic)

**Comment by ICE0124** [comment]
Torboxxxxxx +1

**Comment by mmarquez661** [comment]
We need this asap.

**Comment by Mikeyeahh** [comment]
Yes please implement, huge feature request.

**Comment by YouWishh** [comment]
We need this now. Syncler is useless at the moment.

**Comment by synclerd** [comment]
It has been added in v2.0.0.39 beta.
