### ISSUE TITLE
Hallo, guten Tag, das Programm funktioniert nicht. Ich hoffe auf eine schnellstmögliche Lösung

### ISSUE THREAD

**Issue by mahmoudhussein1994** [synclerd/syncler#151]
[](url)
![Uploading Screenshot_2024-11-24-13-54-34-879_com.syncler.jpg…]()

**Comment by brentonv** [comment]
https://x.com/RealDebrid/status/1859673163681960169

**Comment by mahmoudhussein1994** [comment]
Ich habe nichts verstanden
