### ISSUE TITLE
RD workaround

### ISSUE THREAD

**Issue by brentonv** [synclerd/syncler#152]
Can the developer please implement Tikipeter's RD workaround?

https://github.com/umbrellaplug/umbrellaplug.github.io/commit/b463093877ee2bb3c4ba87b4251f9b4fc91ae847

**Comment by synclerd** [comment]
It has been added in v2.0.0.39 beta.

**Comment by brentonv** [comment]
I saw the update and appreciate this very much but can you please also patch the stable version which will assist the majority of users, thank you

**Comment by HeisenbergXYZ** [comment]
> It has been added in v2.0.0.39 beta.

Installer still gives .34 beta.
Where do we get .39?

**Comment by HeisenbergXYZ** [comment]
> > It has been added in v2.0.0.39 beta.
> 
> Installer still gives .34 beta. Where do we get .39?

Never mind, I found it via Syncler Discord channel.

**Comment by JimQ4** [comment]
Thanks for the update to Beta version. Are there plans to add it to the stable version? It would be greatly appreciated.

**Comment by GrantMitchellUK** [comment]
Would really appreciate this being implemented as an update to the stable release too

**Comment by tk1251** [comment]
Thanks for the update sounds wonderful!

**Comment by safc10boxer** [comment]
Can you please fix rd it would be greatly appreciated

**Comment by JonathanAkaJD** [comment]
I would much like to see this added to the stable build too. I know it may be a little extra work, but so so so many I know prefer the stable to the beta. I know one day the stable will ultimately update the what is the beta, but in the mean time it would be nice to have the workarounds added to the currently stable build of syncler. My elderly parents are a perfect example of this. I can't just throw bets on them in the state it is. They will call me 300x a month just about tv.. I appreciate all your hard work dev, I'm only trying to share with you the importance the old stable still holds in the overall experience many of use have come to use daily

**Comment by Doxiedoggie2358** [comment]
This would as awesome to have RD back.  I would fully love to have this in a sable version.  Thanks to the team.

**Comment by muzicman** [comment]
As a paid application,  we would greatly appreciate it if this was implemented in the stable version ASAP. Thank you.

**Comment by mrlegendneo** [comment]
We appreciate all your hard work can you please implement the work around for stable

**Comment by Gavsmithson** [comment]
Would be brilliant if this could be implemented 👍

**Comment by Shaneukuk** [comment]
This would be great if added to the stable version, thank you

**Comment by Itfdff9** [comment]
Please release for stable

**Comment by Itfdff9** [comment]
With the beta fix how likely is it that rd will get flagged again with it?

**Comment by JoJoMo3** [comment]
This would be a great help to many if added to stable, appreciate all this team does!

**Comment by Ezman123** [comment]
Thank you for all your hard work on this wonderful app, rd patch added to stable would be wonderful and greatly appreciated. Thank you for everything.

**Comment by Juky26** [comment]
Would it be possible to release it to the stable version please as I'm assuming majority of people will be using the stable version. Appreciate your time and effort. Thanks

**Comment by HeisenbergXYZ** [comment]
Guys don't be afraid to go with the Beta. There are no issues. Working very well. UI much better.

**Comment by Lyn61956** [comment]
I'm not savvy enough to go Beta but sure would appreciate the patch when stable is updated. 
Thanks for everything

**Comment by HeisenbergXYZ** [comment]
> I'm not savvy enough to go Beta but sure would appreciate the patch when stable is updated. 
> Thanks for everything 

You don't need to be. Everything is straight forward. 
Btw I'm not affiliated with Syncler, just a regular user from the beginning.

**Comment by Cavegurl** [comment]
Thank you for all the hard work. It is very much appreciated. I would also love to see the fix applied to the  stable version. Again, many thanks.

**Comment by TheCWarner** [comment]
A patch for Stable would be AMAZING please as most of us use stable.

**Comment by vjkumar833** [comment]
Please update STABLE version with similar fix. Thank you for your hardwork

**Comment by wags1** [comment]
This request should not be closed! This needs to be added to stable.

**Comment by Dracermax** [comment]
Thanks I stayed with them

**Comment by Dracermax** [comment]
Thanks everyone I stayed with ya

**Comment by Ferdberfle** [comment]
Thanks for all your hard work.
Please update Stable version with a similar fix.

**Comment by Shookup2** [comment]
Love the work all the team does 👍

**Comment by mflan1066** [comment]
Lets do it, Great App.

**Comment by markcfc** [comment]
Please can you find a fix for the stable version, thanks

**Comment by redtoppaul** [comment]
Please add the fix to stable, thanks

**Comment by Slippknott** [comment]
Thank you !!!

**Comment by Slippknott** [comment]
Thank you for update

**Comment by Jumbodan** [comment]
Please add RD workaround to stable

**Comment by z0ne3** [comment]
Please apply to stable version. Thanks!

**Comment by HeisenbergXYZ** [comment]
Guys, I agree with all of you that Dev should implement this to the stable version, but I also don't see the reason why you shouldn't install and use fully working solution, which is Beta v39 right now...

**Comment by Fullsp** [comment]
Please can the stable version be updated too?

**Comment by Streamer72** [comment]
PLEASE ADD IT TO STABLE VERSION, THANKYOU

**Comment by steelgtr** [comment]
Please, and Thank you  :)

**Comment by Manu7924** [comment]
Please can add to stable thank you for the hard work

**Comment by machoosh** [comment]
Thank you !  I have Beta v39 installed and sticking with RD.

**Comment by KILLZONE1313** [comment]
Cherrs

**Comment by Jungleted67** [comment]
Please, please, please release for the stable version.

**Comment by 6521** [comment]
Please add work around to stabe. Thanks for all you do.

**Comment by Mijen99** [comment]
Using the Beta at the moment, but prefer the stable would be awesome if this could get added too stable!

**Comment by tonka199** [comment]
please use the workaround and thank you for you hard work

**Comment by FrankY316** [comment]
Thank you for helping to solve issue much appreciated

**Comment by steelgtr** [comment]
Keep it going!

**Comment by westdg77** [comment]
Im dying over here without my syncler working properly.  Would love the RD fix.

**Comment by Mike130924** [comment]
Using beta atm but would much prefer RD fix to happen to stable. Much appreciated

**Comment by broly1987** [comment]
Please stable version

**Comment by Grumpa27** [comment]
I've been with you since day one. I feel that the sooner you could get this to stable the better it would be.
People panic and scatter like mice. We can not afford to have them jump to other options/apps. If they leave just to get their rd fix you will not get them back. I'm not affected as I have premiumize but am also adept using rd with magnets but for the less technically inclined it needs to be fixed sooner rather than later.
If you could add the hot fix to stable as a push update it would be greatly appreciated.
thanks dev

**Comment by Juky26** [comment]
I second that been with syncler from day one and even when it was TVZIon. Not going to lie through various platforms I discovered other apps have put a solution in pretty much straight away and you don't even pay for them apps. I'd have thought cz this is a paid app things would've moved more faster.

**Comment by HeisenbergXYZ** [comment]
> I second that been with syncler from day one and even when it was TVZIon. Not going to lie through various platforms I discovered other apps have put a solution in pretty much straight away and you don't even pay for them apps. I'd have thought cz this is a paid app things would've moved more faster.

Have in mind that you have Syncler working with RD as before. You'd just need to put some effort (15min of your time) to download and set up Beta version (working without any noticable issues). You can even run it alongside of Stable. I assure you, once you do this you will not go back to Stable even if it's fixed.
On another note, Dev closed this thread couple days back, so I am not even sure that he got your message. If I were you, hoping to get Stable fixed, I'd look for more info on Discord or Reddit. Just a friendly suggestion...

**Comment by techy66** [comment]
Please on stable version. Really appreciate it

**Comment by kaufman2000** [comment]
Please add to the stable version! Keep up the good work
