### ISSUE TITLE
no links, a popup says real-debrid may have problems (I just renewed-checked, working fine)

### ISSUE THREAD

**Issue by jazluvr449** [synclerd/syncler#154]
I just renewed my real debrid account, successfully, worked great for a couple days, now ican't get any more than 25 links, i click on one, and it tells me real debrid may have problems, I check on settings, says debrid is fine and active, i tried using around 10 content providers, nada.
I switched back to the one that was working, validated it back in june. I tried to contact the vendor, today, haven't heard from him yet. What's going on?
Btw, i have an nvidea shield tv, 2015...still working great 10 years old!

Renewed syncler sub not long ago also, been working great upto the point I re-upped my real debrid acc, which syncler says is working fine. Ready to pull my hair out....

**Comment by synclerd** [comment]
Update to the latest version 1.3.8.2
