### ISSUE TITLE
1.3 Beta - TV/Movie Ratings

### ISSUE THREAD

**Issue by ghost** [synclerd/syncler#2]
The spacing between ratings is unpleasing to the eye. 
I realize this is probably to leave room for Rotten Tomatoes # of users, but if it's not there it just looks wrong.
One solution to make everything cleaner would be to drop # of ratings all together and have the ratings constantly spaced.
![Syncler BETA_20210617_135818](https://user-images.githubusercontent.com/71285381/122479455-b8f16480-cf90-11eb-9401-8151f25510d5.png)

**Comment by synclerd** [comment]
Fixed next beta build.
