### ISSUE TITLE
Can't Scroll to Bottom

### ISSUE THREAD

**Issue by Sn3akySl0th** [synclerd/syncler#23]
Bottom part of the episode page is cut off. See image. You can't see the titles of the shows.

![Screenshot_20210818-084121](https://user-images.githubusercontent.com/9593304/129899968-b722a884-e1fa-4c3c-be8f-60ab3047547a.png)

**Comment by sxiy** [comment]
Please attach a video of reproducing the bug.

**Comment by Sn3akySl0th** [comment]
I have attached a video.

**Comment by Sn3akySl0th** [comment]
It's not letting me post a video. Only image

**Comment by sxiy** [comment]
Upload the video to [streamable](https://streamable.com/upload-video).

**Comment by clefebvre81** [comment]
Here you go.

**Comment by Sn3akySl0th** [comment]
https://streamable.com/mdsgd2

**Comment by sxiy** [comment]
This is the end of the page.

To show item details, enable `Settings > Visuals > Details page > Thumbnail info`.

To change the size/orientation of the similar row, use the size slider/backdrop toggle respectively, both are located in the same Details page section.

**Comment by Sn3akySl0th** [comment]
Okay thanks, that worked. Changed those in the live version didn't change those is the beta. Didn't realize that was what those settings did.
