### ISSUE TITLE
1.3 Beta - ClearArt

### ISSUE THREAD

**Issue by ghost** [synclerd/syncler#3]
Make ClearArt bigger and drop movie tagline "Hello Cruel World".  It makes it cluttered.
![Syncler BETA_20210617_135818](https://user-images.githubusercontent.com/71285381/122479683-1c7b9200-cf91-11eb-9d95-38b704c7523f.png)

**Comment by inb4after** [comment]
Clearlogo is on the small side, yeah

Tagline could be moved to just above plot instead of removing it completely.

**Comment by oathzed** [comment]
I'm not sure I agree with with one. I think the clear art logo is a good size.
