### ISSUE TITLE
1.3 Beta - Trakt Home Page Ratings

### ISSUE THREAD

**Issue by ghost** [synclerd/syncler#5]
Trakt rating on home are /100, when Trakt should be /10. The previous star rating looked much cleaner. 
Moving it to the date/run-time line would clear up the negative space between genre and description. That or add the other ratings similar to detail page. 
![Syncler BETA_20210617_213618](https://user-images.githubusercontent.com/71285381/122498609-097ab900-cfb5-11eb-9107-c6ac92f333ff.png)
![Syncler BETA_20210617_213634](https://user-images.githubusercontent.com/71285381/122498618-0e3f6d00-cfb5-11eb-93cb-a8489429acf5.png)

**Comment by synclerd** [comment]
Fixed next beta build.
