### ISSUE TITLE
Feature Request: Caching the link for second time playing the video

### ISSUE THREAD

**Issue by xenstar** [synclerd/syncler#61]
If the first time we search a link through providers and we watch a show for 20 minutes, 2nd time when click on resume button, why again need the providers to search the links? 
We can just save that link in the resume button, so 2nd time it will play quickly from the same link we selected on first time from our debrid provides. Every time searching a link through the providers is time-consuming. I mostly have 15-20 mins time during lunch and dinner breaks. I want to play something quickly, so please add this function. It's not that hard and complicated. Please admin add it. 

![Screenshot_2022-04-02-12-26-24-586_com syncler](https://user-images.githubusercontent.com/55502651/161366340-6330d139-6b95-4d76-8d77-b3fa3588be74.jpg)

Another feature the dev can easily implement is "Trakt scribbling". Not sure why he is not adding this feature as well. 

Please DEV add this two feature, and make syncler+ perfect and almost similar to Netflix.

**Comment by xenstar** [comment]
I was hoping this would come in the latest update. Although you have introduced bouncy cache, but still it loads the links again, whereas if we click on the resume button again, it could just ask, play from the last link or search again from the cache. 

Please bring it. It would make the user experience similar to Netflix with this one function.

**Comment by synclerd** [comment]
Check beta 2.0 for local source cache. 
Trakt scrobbling is down the line. Create separate issue or upvote existing.

**Comment by xenstar** [comment]
> Check beta 2.0 for local source cache. Trakt scrobbling is down the line. Create separate issue or upvote existing.

Thanks for this, but you made it quite late; switched to emby now.
