### ISSUE TITLE
[Beta] Syncler 1.3.5 - Cache server

### ISSUE THREAD

**Issue by brentonv** [synclerd/syncler#66]
Enabling the new source cache option often causes the application to crash when selecting a source during search, or after the search process has completed.

If "Auto select source" is enabled this works fine, but manually selecting a source will usually crash the app. It seems ok with titles that have limited results or titles which are slow to collect results. 

Also increasing/decreasing resolver threads seems to make no difference, and this has been confirmed with multiple users and various devices including Samsung Galaxy, Shield Pro and Fire TV Stick

**Comment by synclerd** [comment]
Please check 1.3.5.2 beta

**Comment by brentonv** [comment]
> Please check 1.3.5.2 beta

Yes the crashing has been fixed and instantly getting enormous amounts of links with this new feature, tested on Samsung Galaxy, Shield Pro and Fire TV Stick. 

Much appreciated[👍](https://emojipedia.org/thumbs-up/)

**Comment by brentonv** [comment]
Just an update to this, it seems changes made to Syncler v1.3.5 Beta 2 may have subsequently caused a problem with one of the popular Kosmos providers new offline feature.

An issue has been raised with on that developers GitHub page
