### ISSUE TITLE
Trakt Featured lists not displaying

### ISSUE THREAD

**Issue by ryanpasco** [synclerd/syncler#67]
I did a fresh Install on a new device and am still getting the same results, I have no idea what is wrong here.

When Selecting TRAKT,  MOVIES and TV show up fine, But if I select FEATURED LISTS it only displays the text, never populates POSTERS/THUMBNAILS.  Then if you click in to any of the lists it throws an error.

![Screenshot_20220607-125057](https://user-images.githubusercontent.com/107066197/172439497-fecde711-e4de-41a3-ab4d-0c97842eca55.jpg)
![Screenshot_20220607-125051](https://user-images.githubusercontent.com/107066197/172439503-36a124fb-6fde-4f44-b211-8046c9d8d4c0.jpg)

**Comment by brentonv** [comment]
I haven't experienced this. Try testing with VPN or CloudFlare DNS

**Comment by synclerd** [comment]
Cannot reproduce.
