### ISSUE TITLE
[Beta] Icon Broken on OxygenOS

### ISSUE THREAD

**Issue by GR3YH4TT3R93** [synclerd/syncler#68]
![Screenshot_2022-06-08-04-17-58-11_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/76727386/172607948-cb4608e1-9818-4ebd-943b-393fdf88d4d3.jpg)
The beta icon isn't scaling to the correct icon size

**Comment by synclerd** [comment]
Please check 1.3.5.2 beta

**Comment by GR3YH4TT3R93** [comment]
Fixed! Thanks!
