### ISSUE TITLE
Slower search

### ISSUE THREAD

**Issue by ciwy85** [synclerd/syncler#72]
I did notice the increase in time between starting the search and the time when any of the links shiw up, between stable and both betas? On both my galaxy s21 and shield Pro it went from 3sec on stable to 6sec on beta. Both have same settings and source list refresh frequency set to 0. I know it's not much but it's 100% increase. Could it be because of the slower cache server in beta compered to one (provider name redacted) uses in stable?

**Comment by synclerd** [comment]
This is normal. As the the cache server request is an additional request. This will be fixed in the new upcoming provider scheme. In the mean time, disabling caching in providers (within the package) may mitigate the issue.
