### ISSUE TITLE
S+ code can break backup/restore

### ISSUE THREAD

**Issue by BlackChee** [synclerd/syncler#76]
When entering S+ code with lowercase on one  device and upper case on another, they don't see each other's backups.

**Comment by BlackChee** [comment]
>

**Comment by Alphanumbers** [comment]
Yes this is annoying. If S could automatically uppercase this code when it’s entered it would stop this.

**Comment by synclerd** [comment]
Should be fixed now. Make sure to delete all old backups and test it.
