### ISSUE TITLE
[BUG] Fail to scrape (No Results)

### ISSUE THREAD

**Issue by BlackChee** [synclerd/syncler#77]
On the scraping/resolving screen, I am often immediately getting a "No Results" message. I then have to kill and restart the app to get scraping to work again.

Version 1.3.5.1
Nvidia Shield

**Comment by ciwy85** [comment]
Same here, but there is no need to kill the app just go back and try scaping again.

**Comment by BlackChee** [comment]
> Same here, but there is no need to kill the app just go back and try scaping again.

Unfortunately, I've tried rescraping several times and it doesn't fix the issue.. Rescraping would work sometimes when using a different package and getting the "No Sources" message.

**Comment by Willie4040** [comment]
This just happened to me, I cleared the cache with no luck. It was working and then with no reason started saying "No results".  This used to happen every once and awhile and I'd just have to close it and reopen it but now that doesn't work.


Version 1.3.5.1 
Nvidia Sheild

**Comment by synclerd** [comment]
Check beta 2.0
