### ISSUE TITLE
Kodi a4kSubtitles IMDB ID not provided when using "Play With Kodi" or "Open With Kodi"

### ISSUE THREAD

**Issue by DaisyF8** [synclerd/syncler#78]
I may be wrong but in my testing using a4kSubtitles only finds subtitles when Kodi is the default player.

When another player is default, AND you pick Kodi via "Play With" ---> It seems IMDB Id is not proviided.

Or is it me ?

**Comment by synclerd** [comment]
Play with/Open with options are android specific and does not allow handing over additional data.
