### ISSUE TITLE
Package Auto Update Does Not Work

### ISSUE THREAD

**Issue by wags1** [synclerd/syncler#83]
Package auto update does not work when enabled no mater what time period is selected. It doesn’t work on either of my 2019 Nvidia Shields. It has never worked. Tried all normal troubleshooting, uninstall/reinstall Syncler using provisioned installer, uninstall/reinstall provider package(s), disable/enable package auto update setting, tried different time periods from 1 day to several days, force closed and restarted Syncler, etc. Manually updating provider package(s) works fine.

**Comment by synclerd** [comment]
Please check beta 2.0
