### ISSUE TITLE
Issues & Future Updates Syncler

### ISSUE THREAD

**Issue by synergyagency** [synclerd/syncler#85]
Hey Syncler Dev,

Just to let you know these are the bugs i have found and some updates i would like to be added. 
(Have just put it in one message so its easier for you)

**Issues:**
- Up next, Details & TMDB Fan art logo pics not showing up

**Future Improvements:**
- Please please please get Trakt scrobbling
- Trakt calendar (this would be amazing)
- Faster scrape times with javascript update!

Ps, when do you think the next update will be for this as well?

Thank you and keep up the great work!

**Comment by synclerd** [comment]
Create separate feature request for each please. Faster JS engine is released in 2.0 Beta.
