### ISSUE TITLE
Skip forward/backward amount customization 

### ISSUE THREAD

**Issue by IsserleyOne** [synclerd/syncler#88]
At the moment, you can only skip forwards or backwards during playback by 1 minute. It would be brilliant if this could be a customizable setting, where we could change the amount of time skipped (say for example to 30 seconds or 20 seconds, etc). As it stands, if I miss a line of dialogue and want to rewind, I have to sit through a whole minute of stuff I've already seen just to catch that one line.

**Comment by synclerd** [comment]
A setting is already there in Settings > Playback > Exo
