### ISSUE TITLE
While searching for sources, you can't move down to select unless you hold the "down" button 

### ISSUE THREAD

**Issue by Zizou3000** [synclerd/syncler#94]
While searching is still ongoing (and full search can take a long time), you are "stuck" at the top unless you hold the button (down) to force movement.

Not a big deal to fix I think and it is annoying. 

Thank you

**Comment by synclerd** [comment]
It keeps you at the top of the list by intention. Otherwise any source you select will stay on top and new sources appearing above it will not be visible until you press up.
